- app/views/settings/_redmica_ui_extension.html.erb
- app/views/ui_extension/_burndown_chart.html.erb
- assets/burndown_chart/javascripts/burndown_chart.js
- assets/burndown_chart/stylesheets/burndown_chart.css
- config/locales/en.yml
- config/locales/ja.yml
- init.rb
- init_redmica_ui_extension.rb
- lib/burndown_chart/hook_listener.rb
- lib/burndown_chart/versions_helper_patch.rb
- test/helpers/versions_helper_patch_test.rb
- test/system/burndown_chart_test.rb
I propose a feature to visualize the changes of Open / Close issues in the version detail using 'Burndown chart'.
> Add Burndown chart on version detail

- lib/burndown_chart/versions_helper_patch.rb
- test/helpers/versions_helper_patch_test.rb
バージョンの「期限」が「開始日」よりも早いとideal線が以下のようにプロットされる。
「期限」が「開始日」よりも早い場合は、以下のようにideal線をプロットしないよう変更してはどうでしょうか？
> Make it possible to hide ideal line when due_date earlier than start_date

- assets/burndown_chart/javascripts/burndown_chart.js
チケット数が60件弱を超えると、以下のようにY軸の目盛りが重なり合ってしまう。
Chart.jsで指定できるパラメータ **autoSkip** を **true** に変更することで、Y軸の目盛りが重なり合う現象を回避します。
```diff
-          ticks: { min: 0, max: y_lim, stepSize: 1 }
+          ticks: { min: 0, max: y_lim, stepSize: 1, autoSkip: true }
```
変更後は以下のようにチャートのY軸が重なり合わないようになります。
> Change to auto skip the Y-axis ticks

- app/views/settings/_redmica_ui_extension.html.erb
- app/views/ui_extension/_burndown_chart.html.erb
- init_redmica_ui_extension.rb
- lib/redmica_ui_extension/setting_patch.rb
- lib/searchable_selectbox/hook_listener.rb
- test/system/burndown_chart_test.rb
- test/system/searchable_selectbox_test.rb
- test/unit/setting_patch_test.rb
背景:
既存の仕組みではinit.rbで `settings default: {'searchable_selectbox' => {'enabled' => 1}, 'burndown_chart' => {'enabled' => 1}}` と書いていてデフォルトが有効状態になっているように見えますが、  
これはSettingレコードが無いときに入れる値なので、すでに利用を始めた状態で新しく機能を追加した場合はここに `'new_feature' => {'enabled' => 1}`と書いていても何もデータベースに入りません。  
設定がない場合は有効扱いしてほしいという要望があがったため、対応。
----
設定がない場合は有効扱いするために、値が存在したら有効という現在の判定を
* 値がnilだったら有効
* 値が1だったら有効
* 値が0だったら無効
のように変更しました。  
また、現在は無効設定にしたとき値がnilになるため、hidden_tagを足すことでチェックを外したときに0が入るように変更しています。
(今後はデフォルト無効にしたい機能が出てくるかもしれませんが、現時点ではデフォルトで有効にしたくないような機能を入れる予定が無いためこのような実装にしています。必要になったら直します。)
----
レビュワーには @yui-har さんと @takenory さんを指定していますが、お二人のうちお一人に見ていただいたらマージしようかなと思っています。
> Change the default enabled setting value to true

- app/views/ui_extension/_burndown_chart.html.erb
- assets/burndown_chart/javascripts/burndown_chart.js
- assets/burndown_chart/stylesheets/burndown_chart.css
https://github.com/redmica/redmica_ui_extension/pull/9 の変更により `autoSkip: true` が優先されることによって
チケット数が少ない場合に以下のようにY軸に不要な目盛り（.5）が表示される。
チャートにプロットするデータサイズに応じて、`autoSkip: true` と `stepSize: 1` を切り替えるよう変更します。
> Enable to switch Y-axis 'autoSkip' or 'stepSize' depending on the data size

- test/helpers/versions_helper_patch_test.rb
RedMicaのmasterブランチ（Rails6）でテストが失敗する問題の改善です。
テストに使用するIssueを作成したオブジェクトとDBに登録後のlock_versionが異なるため
テストデータの更新時にエラーとなり、テストが失敗していました。
対象のIssueオブジェクトをリロードすることで対処しています。
> Fix lock_version error on test

- test/helpers/versions_helper_patch_test.rb
Github Actionsで実行したテストが次のように失敗していました。 (https://github.com/ishikawa999/redmica_ui_extension/runs/2405924893?check_suite_focus=true)
```
RAILS_ENV=test bundle exec rake test TEST=plugins/redmica_ui_extension/test
shell: sh -e {0}
Run options: --seed 63846
.E
Error:
VersionsHelperPatchTest#test_issues_burndown_chart_data_should_return_chart_data_without_ideal_when_due_date_earlier_than_start_date:
NoMethodError: undefined method `status=' for nil:NilClass
plugins/redmica_ui_extension/test/helpers/versions_helper_patch_test.rb:149:in `test_issues_burndown_chart_data_should_return_chart_data_without_ideal_when_due_date_earlier_than_start_date'
bin/rails test plugins/redmica_ui_extension/test/helpers/versions_helper_patch_test.rb:143
.E
Error: …
```
> Add issues fixtures to VersionsHelperPatchTest

- .github/scripts/setup-redmica.sh
- .github/templates/application_system_test_case.rb
- .github/templates/database-mysql.yml
- .github/templates/database-postgres.yml
- .github/templates/database-sqlite.yml
- .github/workflows/test.yml
このリポジトリにpushしたとき、forkリポジトリからこのリポジトリに対してプルリクエストを作ったとき、CI実行履歴から手動で再実行を選択したときに
```
RAILS_ENV=test bundle exec rake test TEST=plugins/redmica_ui_extension/test
RAILS_ENV=test bundle exec rake test
```
を実行します。
**テスト対象:**  
RedMica:
* https://github.com/redmica/redmica のmasterブランチ最新のRedMica
* redmica/redmica:latestで動いているリリース済み最新バージョンのRedMica
DB:
* postgres:11
* mysql:5
* sqlite
の各組み合わせごとにテストを実行します。(6パターン)
**これを動かすための環境作りについて説明:**
実行速度を上げるためにRedMicaが動くために必要なライブラリが入っているredmica/redmica:latestイメージの上でテストを実行します。
redmica/redmica:latestにはproductionモードで動くためのdatabase.ymlやgem、ライブラリしか入っていないためsetup_redmica.shで必要なコマンドを実行しています。
また、`masterブランチ最新のRedMica`はredmica/redmica:latestの/usr/src/redmineディレクトリの中身をまるごとGitHubから取得したmasterブランチ最新のコードに置き換えることで動かしています。(かなり強引で、今後上手く動かなくなる可能性あり) …
> Add GitHub actions configration

- assets/searchable_selectbox/javascripts/searchable_selectbox.js
#17 
問題の内容:
* searchable_selectbox機能が有効になっているとき、セレクトボックスに対するchangeイベントが2回発生する
* changeイベントを2回発生させているのは、https://github.com/redmica/redmica_ui_extension/issues/17#issuecomment-922279390 の問題の回避策(select2で作られた要素に変更を加えたとき、jqueryのchangeイベントは発生してもaddEventListenerで設定したネイティブなイベントが拾えない)
* ただ、issues_templateプラグインの0.3-stableブランチのコードをはじめとして、イベントが2回発生することにより正しく挙動しないケースもある
今回の変更:
根本的な問題の解決は難しいため、ネイティブなイベントが存在するときにのみイベントを2回発生させるように変更します。
これによって、ネイティブなイベントが存在しないときは通常通りの動きになるためイベントが2回発生することによる多くの問題は解決するはずです。
ネイティブなイベントが存在することを取得する方法は関数として提供されていないため、 `EventTarget.prototype.addEventListener` を上書きし、addEventListenerが動いたという情報を追加するdata属性をelementに対して追加するようにしています。
@yui-har レビューをお願いいたします。
>  Changed to trigger the change event twice only when there is a native change event

- assets/searchable_selectbox/javascripts/searchable_selectbox.js
問題の再現方法
* redmine_issue_templatesプラグインをインストール (1.0.0以上)
* 管理 > プラグイン > Redmine Issue Templates pluginの設定 で 「標準/カスタムフィールドの利用を可能にする」にチェックを入れ保存
* チケットテンプレートモジュールが有効になったプロジェクトで、「標準/カスタムフィールドの利用を可能にする」機能をつかって担当者(などのセレクトボックスで値を選択するフィールド)の値を上書きするテンプレートを作成する
* チケット新規作成画面で作成したチケットテンプレートを適用すると、担当者のセレクトボックスに上書きされた値が表示されない（セレクトボックスをクリックすると上書きされた値で選択できていることが分かるが、閉じているときの表示に反映されていない）
修正前: テンプレート適用後のセレクトボックス
修正後: テンプレート適用後のセレクトボックス
> Support redmine_issue_templates plugin (Built-In / Custom Fields feature

- .github/templates/application_system_test_case.rb
- init.rb
- test/helpers/application_helper_patch_test.rb
- test/helpers/versions_helper_patch_test.rb
- test/system/burndown_chart_test.rb
- test/system/mermaid_macro_test.rb
- test/system/searchable_selectbox_test.rb
- test/unit/setting_patch_test.rb
This change removes `File.expand_path` and `__FILE__` from the parameter of `require`.
The following is an example.
``` diff
diff --git a/init.rb b/init.rb
index 942a97a..acf43d1 100644
--- a/init.rb
+++ b/init.rb
@@ -1,6 +1,6 @@
-require File.expand_path('../init_redmica_ui_extension', __FILE__)
+require_relative 'init_redmica_ui_extension'
Redmine::Plugin.register :redmica_ui_extension do
requires_redmine version_or_higher: '4.1'
```
> Use `require_relative` to avoid building an absolute path for `require`

- assets/stylesheets/searchable_selectbox/searchable_selectbox.css
Due to the impact of Propshaft support, there is an issue in RedMica 3.0 where the magnifying glass icon does not appear when the searchable select box feature is enabled.
I have decided to remove the magnifying glass icon since it is still clear that the select box is searchable without it.
Additionally, for the Bleuclair theme, the magnifying glass icon and padding are added on the theme side, so the display remains unchanged.
|selectbox before changes|selectbox after changes|selectbox after changes(with bleuclair theme)|
|----|---|---|
|<img width="382" alt="screenshot 2024-07-04 16 29 03" src="https://github.com/redmica/redmica_ui_extension/assets/14245262/0dab41ed-7b1d-463d-b8d6-bc419d82dde2">|<img width="382" alt="screenshot 2024-07-04 16 28 05" …
> Remove magnifier icon in select2 search field

- assets/stylesheets/searchable_selectbox/searchable_selectbox.css
Fixes an issue where the height of the empty option is reduced, as shown in the image.
This problem was probably caused by https://www.redmine.org/issues/40210.
> Fix small height of empty option in searchable select boxes

- .github/scripts/setup-redmica.sh
- .github/workflows/test.yml
This PR includes the following changes:
* Change the test target to RedMica 3.0.1 and Ruby 3.3
* Add a temporary workaround to avoid test failures due to [the change from unprocessable_entity to unprocessable_content in Rack 3.1.0](https://github.com/rack/rack/pull/2137)
* In Rack 3.1.0 and later, all tests to verify that the response code is `:unprocesable_entity` fail. More info: https://github.com/hidakatsuya/redmica_ui_extension/actions/runs/9756212264/job/26926081378
* This has been resolved in [the Redmine master branch](https://github.com/redmine/redmine/commit/b803bddb1f32842b0a5ec93640778d902b5f7999), but not yet in RedMica.
> Test against RedMica 3.0.1 and Ruby 3.3

- .github/workflows/test.yml
This PR updates to [actions/checkout](https://github.com/actions/checkout) version to v4. This will suppress the following warnings.
> Update actions/checkout to v4 to suppress the warning

- lib/preview_attachment/application_helper_patch.rb
- test/helpers/application_helper_patch_test.rb
When the "Make attachments previewable" feature of redmica_ui_extension is enabled, adding a Files column to the issue list causes the preview link to not display correctly.
|  before change  |  after change  |
| ---- | ---- |
|  <img width="618" alt="screenshot 2024-09-11 9 00 21" src="https://github.com/user-attachments/assets/020d57a6-1356-4e93-afee-7e972f4bb6d2"> |  <img width="618" alt="screenshot 2024-09-11 9 00 40" src="https://github.com/user-attachments/assets/1d3a3340-5add-4c03-b26a-f86d0662d9d5">  |
**Reproduction steps:**
Enable the "Make attachments previewable" feature in redmica_ui_extension.
Navigate to the issue list view.
Add a Files column to the issue list.
Observe that the preview link is not rendered correctly.
**Fix:**
This pull request resolves the rendering …
> Fix broken preview link rendering in the issue list view

- assets/stylesheets/mermaid_macro/mermaid_macro.css
- test/system/mermaid_macro_test.rb
This pull request fixes the issue where the mermaid macro's SVG does not display when using this plugin with the latest version of Redmine.
The root cause of the issue is that the SVG's width and height are set to `0`, as defined in [this Redmine stylesheet](https://github.com/redmine/redmine/blob/master/app/assets/stylesheets/application.css#L1666-L1668).
This pull request resolves the issue by overriding the mermaid SVG's width and height to `initial`, ensuring that the SVG will render with correct size.
To prevent this issue from occurring again in the future, I have also added a test that verifies the SVG is displayed correctly, and that its width and height are not set to `0`.
* The test will fail if run without the CSS changes.
* After applying the changes, the test will pass as the …
> Fix mermaid macro SVG size issue

- assets/stylesheets/mermaid_macro/mermaid_macro.css
- test/system/mermaid_macro_test.rb
This PR fixes two issues related to div.mermaid svg styling in responsive mode:
* Width issue: In responsive mode, it is correct for the width to change from width: initial to width: 100% to properly adapt to the screen size. To ensure this transition is not blocked, the overriding `width: initial;` style has been removed.
* Height issue: The height remains fixed based on the screen width before entering responsive mode, causing it to exceed the required dimensions and leaving unnecessary blank spaces. To prevent this, the original style has been overridden with `height: auto;`.
> Fix incorrect svg size in responsive mode

- .github/workflows/test.yml
- init.rb
- lib/preview_attachment/application_helper_patch.rb
- test/helpers/application_helper_patch_test.rb
This pull request replace icon 'zoom-in" to SVG image for attachment preview links that's provided by this plugin.
* [`lib/preview_attachment/application_helper_patch.rb`](diffhunk://#diff-bc2fba562e08da3a4e0602220563b38e884173ff2f0415ace357bb226c7496b2L36-R36): Updated the `link_to_attachment` method to use the `sprite_icon` helper for the zoom-in icon, enhancing the attachment preview link.
* [`test/helpers/application_helper_patch_test.rb`](diffhunk://#diff-a5ac8b58555b79516fb065069fb321e0803ad5050cda5d3c0a9bab3e2b54487eL52-R52): Modified the test for `link_to_attachment` to reflect the changes in the attachment preview link, ensuring the SVG icon is correctly included in the generated HTML.
* [`init.rb`](diffhunk://#diff-4afdb3c3c34a069c37756ebaee5883f21565d29c7730ba4565b88aa809d226ccR …
> Support for SVG icons in Redmine6

- .github/workflows/test.yml
This pull request includes a small change to the .github/workflows/test.yml file. The change adds a new matrix configuration for testing with the stable version 3.1 of the RedMica repository.
* Updated `redmica_version` matrix to include version "v3.1.0" alongside "master" in three job configurations. [[1]](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L8-R8) [[2]](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L43-R43) [[3]](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L75-R75)
> Add CI environment using RedMica3.1

- test/helpers/application_helper_patch_test.rb
Fix the test so that it does not fail as follows:
```
Failure:
ApplicationHelperPatchTest#test_link_to_attachment_should_return_preview_link_when_setting_is_enabled_and_class_option_includes_icon_download [plugins/redmica_ui_extension/test/helpers/application_helper_patch_test.rb:53]:
--- expected
+++ actual
@@ -1 +1 @@
-"<a class=\"preview-attachment icon-only icon-zoom-in\" data-bp=\"logo.gif\" data-bp-src=\"imgSrc\" data-url=\"http://test.host/attachments/download/3/logo.gif\" onclick=\"previewAttachment(this);return false;\" href=\"#\"><svg class=\"s18 icon-svg\" aria-hidden=\"true\"><use href=\"/assets/icons-903cd898.svg#icon--zoom-in\"></use></svg></a><a class=\"icon-download\" href=\"/attachments/download/3/logo.gif\">logo.gif</a>"
+"<a class=\"preview-attachment icon-only …
```
> Fix the test so that it works even if the icon path changes

- .github/workflows/test.yml
GitHub Actions tests are currently failing due to `actions/upload-artifact@v3` being deprecated.  
This PR updates it to `actions/upload-artifact@v4` to resolve the issue and ensure the workflow runs successfully.
failed test: https://github.com/redmica/redmica_ui_extension/actions/runs/13276915666
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
- Updated `actions/upload-artifact` from `v3` to `v4` in the workflow files.
> Upgrade actions/upload-artifact from v3 to v4 to resolve deprecation notice

- assets/stylesheets/searchable_selectbox/searchable_selectbox.css
I will remove the max-width setting that was previously applied to the select box when the "Make the selection box searchable" option was enabled.
Due to this max-width setting, the width of the select box did not increase beyond 300px, even when the screen width was larger. As a result, long options that did not fit within the select box could only be fully viewed by opening the dropdown.
|before|after|
|---|---|
|<img width="1920" alt="screenshot 2025-03-03 15 19 18" src="https://github.com/user-attachments/assets/346de7a1-d68f-4f23-a143-bfb893e06180" />|<img width="1920" alt="screenshot 2025-03-03 15 17 56" src="https://github.com/user-attachments/assets/6cb78c51-249a-439d-8087-ce822e4b7f9d" />|
> Remove max-width style for select2 select box
